env:
    credentials: "ENCRYPTED[27ffdc060124f14849a74f50f360d0f0a611318c1a1ba8985da26e948b4b2d65d78e840ccbfc38c968f9715700affb83]"
    rcloneconfig_b64: "ENCRYPTED[1d7e0a5417431d715cf8c1ffc2a80424912c940a62a3076072188ccfdb9855d6865592f7b0184e971d155b7a1d167e72]"
    tokentl: "ENCRYPTED[f399614db101ff55e3fd74abfd30f1686c425d1855aa94105330fdc3dae9b729d2379ca0916a50ee79fff439427eb4d8]"
    idtl: "ENCRYPTED[63b0a23edb0341e865ef37c3d3c69bde6282b5fa76ce6277dee18456026dcb17034bd3acbc6b4723f66aacb7b8f3c054]"
    lunch: lunch lineage_surya-user
    make: mka bacon

task:
  name: "Setting Up, Syncing, Building and Uploading..."
  timeout_in: 115m
  container:
      image: memedo/paiskomom:knjt
      cpu: 8
      memory: 32G

  Build-Env-Setup_background_script:
       - export DEBIAN_FRONTEND=noninteractive
       - mkdir -p ~/.config/rclone
       - echo "$rcloneconfig_b64" | base64 -d > ~/.config/rclone/rclone.conf
       - git config --global user.name "paiskomom"
       - git config --global user.email "midooneteam@gmail.com"
       - echo "$credentials" > ~/.git-credentials
       - git config --global credential.helper store --file=~/.git-credentials
       - mkdir -p ~/ccache
       - rclone copy komom:lineage/ccache.tar.gz ~/ -P
       - cd ~/
       - time tar xf ccache.tar.gz
       - cd ~/

  Storage-Checker_background_script:
      - df -h
      - lsblk
      - ls -l -a -h
      - ./w.sh

  Sync_script:
      - curl -s https://api.telegram.org/bot$tokentl/sendMessage -d chat_id=$idtl -d text="🔄 Start sync Source. . ."
      - mkdir -p ~/rom
      - cd ~/rom
      - sudo curl --create-dirs -L -o /usr/local/bin/repoo -O -L https://storage.googleapis.com/git-repo-downloads/repo
      - sudo chmod a+rx /usr/local/bin/repoo
      - repo init -q --no-repo-verify --depth=1 -u https://github.com/LineageOS-Revived/android.git -b lineage-17.1
      - git clone --depth 1 https://github.com/paiskomom/local_manifest.git -b surya-10 .repo/local_manifests
      - sudo apt-get update && sudo apt-get install -y git-lfs && git lfs install
      - rm -rf .repo/repo && git clone https://gerrit.googlesource.com/git-repo .repo/repo
      - repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8
      - repo forall -c 'git lfs install && git lfs pull && git lfs checkout'
      - curl -s https://api.telegram.org/bot$tokentl/sendMessage -d chat_id=$idtl -d text="✅ Sync Completed!"

  Build_script:
      - export BUILD_USERNAME="haikaru17"
      - export BUILD_USER="haikaru17"
      - export BUILD_HOSTNAME="ubuntu"
      - export BUILD_HOST="ubuntu"
      - sudo ln -sf /usr/share/zoneinfo/Asia/Jakarta /etc/localtime
      - curl -s https://api.telegram.org/bot$tokentl/sendMessage -d chat_id=$idtl -d text="🛠️ Boeild lineage Started! https://cirrus-ci.com/build/$CIRRUS_BUILD_ID"
      - ./collect.sh
      - curl -s https://api.telegram.org/bot$tokentl/sendMessage -d chat_id=$idtl -d text="⏳ Build script selesai. Lanjut ke proses upload ccache atau zip ROM."

  Upload_script:
      - |
        if ls ~/rom/out/target/product/surya/lineage*.zip 1> /dev/null 2>&1; then
            bash upload.sh
            curl -s https://api.telegram.org/bot$tokentl/sendMessage -d chat_id=$idtl -d text="🚀 Build Process Finished!"
        else
            curl -s https://api.telegram.org/bot$tokentl/sendMessage -d chat_id=$idtl -d text="❌ Build Zip not found, skipping rom upload..."
        fi
      - curl -s https://api.telegram.org/bot$tokentl/sendMessage -d chat_id=$idtl -d text="📦 Compressing ccache..."
      - ./ziping.sh
      - curl -s https://api.telegram.org/bot$tokentl/sendMessage -d chat_id=$idtl -d text="📤 Uploading ccache..."
      - rclone copy ~/ccache.tar.gz komom:lineage -P
      - curl -s https://api.telegram.org/bot$tokentl/sendMessage -d chat_id=$idtl -d text="✅ ccache Uploaded Successfully!"
